### ISSUE TITLE
Explain why we recommend specific scanners

### ISSUE THREAD

**Issue by jonasrosland** [hitsave/scanning.guide#1]
From Ethan:
"Will have to ask around but are there really only two good options in the price range here? We should have a further explanation of what you do NOT want in a scanner. The softening filters and all that. So if people have a scanner and aren't going to buy another one, at least to tell them if their's might be suitable for a lower quality scan."

**Comment by hardcorehubz** [comment]
Unfortunately currently for new scanners the Epson V550 seems to be the lowest priced option. The Canon Canoscan 9000F Mark II seems to have been discontinued and Epson V370 as well. However that doesn't mean you can pick up an old scanner from Ebay as long as it is CCD and is capable of 1200DPI. It's impossible to know an exhaustive list of scanners that could work though. Generally as a rule of thumb though if it is capable of CCD it should be capable of 1200DPI.

**Comment by jonasrosland** [comment]
Ethan pointed out that the v550 seems to be off the market as well, so the closest one right now would most likely be the v600 if you're looking to buy a new one.

**Comment by jonasrosland** [comment]
Added more hardware suggestions and a quick why CCD vs CIS: https://dev.scanning.guide/getting-started/what-where-to-buy/, thanks @hardcorehubz.

Closing this for now.
